### ISSUE TITLE
Working Together?

### ISSUE THREAD

**Issue by NWPlayer123** [bigianb/ghidra-ps2ee#1]
I see there's two separate projects adding Emotion Engine support for Ghidra, think maybe y'all should work together? https://github.com/beardypig/ghidra-emotionengine

**Comment by bigianb** [comment]
I hadn't seen that repo ... it's pretty nice ... much nicer than this one :)
I'll make sure I contribute anything there that they are missing (although it seems much more complete right now that this is or probably ever will be :) )
